### ISSUE TITLE
Manual Spawning gems messes up production

### ISSUE THREAD

**Issue by stevenroach7** [stevenroach7/Ceres#12]
If you spawn gems via touching the jackhammer too quickly their production will be messed up. By messed up I mean that the gems will be spawned going directly upwards with a high velocity (well the gem they contact with will now have a high velocity).

**Comment by seanacheng** [comment]
Should we have the gem spawning lag or just not record gem source touches for a little bit after the each touch?

**Comment by stevenroach7** [comment]
I'll edit this when I move the gameplay to its own class. Probably just a slight lag would do the trick.

**Comment by stevenroach7** [comment]
Another issue with this I'm noticing is that if you touch the top part of the hammer, the gem produced flies quickly straight up. I think it is because the initial touch is inside the touch radius of the gem produced so that when you the touch ends, you give it an initial velocity.

**Comment by stevenroach7** [comment]
I think that this might actually be causing the bug and not the gems spawning on top of each other.

**Comment by seanacheng** [comment]
Yeah, I've been testing it out and it didn't seem like it was because they were spawning on top of each other
