### ISSUE TITLE
Red hue around hammer doesn't appear when testing on iPhone 6 device

### ISSUE THREAD

**Issue by stevenroach7** [stevenroach7/Ceres#17]
On my phone (iPhone 6), the red hue appears in the tutorial mode and then goes away when the game begins. I ran an iPhone 6 in the simulator, and the red hue was present during both the tutorial and gameplay. Those with other types of iPhones, is the red hue appearing during gameplay?

**Comment by seanacheng** [comment]
Wow, I forgot about that.  The red hue does not show up at all on my SE.  but I do have a pretty old version of the game, if it was changed at all recently.  In the SE simulator, the hue does disappear during gameplay

**Comment by stevenroach7** [comment]
@seanacheng The red hue doesn't appear during gameplay on the SE simulator for you? It does for me.

**Comment by seanacheng** [comment]
nope, just the sparks

**Comment by stevenroach7** [comment]
Interesting. @seanacheng I noticed on Trello that Matt, Danny, and I have a lot of tasks we are currently working on. Can you do some more testing and see if you can figure out what is gong on?

**Comment by seanacheng** [comment]
yeah, for sure

**Comment by seanacheng** [comment]
@stevenroach7 the hue is only supposed to appear during the tutorial right? because it's the hammerInactive image

**Comment by stevenroach7** [comment]
No, the functions to animate the hammers (which should probably be refactored into one function that takes an enum btw) run the animation which cycles through both the hammerActive and hammerInactive images.

**Comment by seanacheng** [comment]
The problem was that there were two images called hammerInactive, the one in the atlas has no glow and the one in the assets folder has the glow.
