### ISSUE TITLE
Pause button stops working

### ISSUE THREAD

**Issue by dvochoa** [stevenroach7/Ceres#20]
There are times when the pause button becomes difficult to press. One might have to touch only the corner to activate it rather than the button itself. This seems to become more of a problem as the game goes on. One hypothesis might be that once the timer/score enter double or triple digits the button activation area is being moved off screen by the extra digits. This has effected both Steven and I (Both IPhone 6's).

**Comment by stevenroach7** [comment]
Also is an issue in the simulator at times.

**Comment by seanacheng** [comment]
Interesting, i've never reached triple digits, but it works for my phone for two digits.  I also just tried it on the SE and 6 simulator and it works fine at triple digits.  I guess you could try moving the timer over to the right and test it again.

**Comment by stevenroach7** [comment]
Its definitely not as simple as just reaching triple digits. I've found this bug difficult to reproduce intentionally but I'm encountering it sporadically today.

**Comment by seanacheng** [comment]
Yeah, I was just testing for it, it seems to be very random.  But every time it happens for me is when it is triple digits for the score and timer, which is unlikely to happen in real gameplay

**Comment by stevenroach7** [comment]
I've had it happen multiple times when both the score and the timer are not in triple digits. The score has been negative in that case however.

**Comment by stevenroach7** [comment]
Nevermind, just happened when score was positive and timer was 2 digits.
